config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :livros
  root "livros#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/livro.rb
class Livro < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_livro, only: %i[ show edit update destroy]
  def index
    @livros = Livro.all
  end

  def show
  end

  def new
    @livro = Livro.new
  end

  def create 
    @livro = Livro.new(livro_params)
    if @livro.save
      redirect_to @livro
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @livro.update(livro_params)
      redirect_to @livro
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy 
    @livro.destroy
    redirect_to livros_path
  end

  private
    def set_livro
      @livro = Livro.find(params[:id])
    end

    def livro_params
      params.expect(livro: [:titulo, :autor, :ano, :genero])
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Biblioteca" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <nav class="bg-gray-800 text-white fixed top-0 w-full shadow-md">
        <div class="max-w-6xl mx-auto px-4 py-3 flex justify-between items-center">
          <div class="flex items-center gap-2">
            📚 <%= link_to "Biblioteca", root_path, class: "text-xl font-bold hover:text-gray-300" %>
          </div>

          <div class="flex gap-4">
            <% if authenticated? %>
              <%= button_to "Logout", session_path, method: :delete, class: "bg-red-500 px-3 py-1 rounded hover:bg-red-600 cursor-pointer" %>
            <% else %>
              <%= link_to "Login", new_session_path, class: "hover:text-gray-300" %>
            <% end %>
          </div>
        </div>
    </nav>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/livros/_form.html.erb
<%= form_with model: @livro, local: true do |form| %>
  <div class="mb-3">
    <%= form.label :titulo, class: "block text-gray-700 font-medium" %>
    <%= form.text_field :titulo, class: "mt-1 block w-full border border-gray-400 rounded-lg shadow-md focus:ring-2 focus:ring-blue-500 focus:border-blue-600 p-2" %>
  </div>

  <div class="mb-3">
    <%= form.label :autor, class: "block text-gray-700 font-medium" %>
    <%= form.text_field :autor, class: "mt-1 block w-full border border-gray-400 rounded-lg shadow-md focus:ring-2 focus:ring-blue-500 focus:border-blue-600 p-2" %>
  </div>

  <div class="mb-3">
    <%= form.label :ano, class: "block text-gray-700 font-medium" %>
    <%= form.text_field :ano, class: "mt-1 block w-full border border-gray-400 rounded-lg shadow-md focus:ring-2 focus:ring-blue-500 focus:border-blue-600 p-2" %>
  </div>

  <div class="mb-3">
    <%= form.label :genero, class: "block text-gray-700 font-medium" %>
    <%= form.text_field :genero, class: "mt-1 block w-full border border-gray-400 rounded-lg shadow-md focus:ring-2 focus:ring-blue-500 focus:border-blue-600 p-2" %>
  </div>

  <div>
    <%= form.submit "Salvar", class: "w-full bg-green-500 text-white py-2 rounded hover:bg-green-600" %>
  </div>
<% end %>

app/views/livros/edit.html.erb
<div class="max-w-lg mx-auto bg-white rounded-xl shadow-md p-6">
  <h1 class="text-3xl font-bold mb-4">Editar Livro</h1>
  
  <%= render "form", livro: @livro %>
  <%= link_to "← Cancelar", livros_path, class: "text-gray-600 hover:text-gray-800 mt-3 inline-block" %>
</div>

app/views/livros/index.html.erb
<div class="max-w-3xl mx-auto mt-10">
  <h1 class="text-4xl font-bold mb-6">Livros</h1>

  <% if authenticated? %>
    <%= link_to "Novo Livro", new_livro_path,
        class: "inline-block mb-4 bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600" %>
  <% else %>
    <%= link_to "Login", new_session_path,
        class: "inline-block mb-4 bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600" %>
  <% end %>

  <div class="space-y-3">
    <% @livros.each do |livro| %>
      <div class="bg-white border border-gray-300 shadow-lg rounded-lg p-4 hover:shadow-xl hover:bg-gray-50 transition">
        <%= link_to livro.titulo, livro, class: "text-lg font-sans text-gray-800 hover:text-gray-600" %>
      </div>
    <% end %>
  </div>
</div>

app/views/livros/new.html.erb
<div class="max-w-lg mx-auto bg-white rounded-xl shadow-md p-6">
  <h1 class="text-3xl font-bold mb-4">Novo Livro</h1>
  
    <%= render "form", livro: @livro %>
    <%= link_to "← Cancelar", livros_path, class: "text-gray-600 hover:text-gray-800 mt-3 inline-block" %>
</div>

app/views/livros/show.html.erb
<div class="max-w-2xl mx-auto mt-10 bg-white border border-gray-300 shadow-lg rounded-lg hover:shadow-xl hover:bg-gray-50 transition p-6">
  <h1 class="text-3xl mb-4 text-gray-800"><%= @livro.titulo %></h1>

  <div class="flex gap-3 mb-4">
    <%= link_to livros_path, class: "flex items-center gap-2 text-gray-700 hover:text-gray-900 font-medium" do %>
      ← Voltar
    <% end %>


    <% if authenticated? %>
      <%= link_to "Editar", edit_livro_path(@livro), class: "bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600" %>

      <%= button_to "Deletar", @livro, method: :delete,
            data: { turbo_confirm: "Você realmente deseja deletar este livro?" },
            class: "px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600" %>
    <% end %>
    
  </div>
</div>